# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-30 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterContact',
            fields=[
                ('id', models.BigAutoField(db_column='id_register_conctact', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=500)),
                ('email', models.CharField(db_column='email', max_length=500)),
                ('address_id', models.ManyToManyField(db_column='id_address', to='address.Address')),
                ('phone', models.ManyToManyField(db_column='id_phone', to='phone.Phone')),
            ],
            options={
                'db_table': 'registerContact',
                'managed': True,
                'default_permissions': ('view',),
            },
        ),
    ]
