# Generated by Django 2.1 on 2018-09-10 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_contact', '0002_auto_20180910_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registercontact',
            name='phone',
            field=models.ManyToManyField(db_column='id_phone', null=True, to='phone.Phone'),
        ),
    ]
