# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-30 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(db_column='id_address', primary_key=True, serialize=False)),
                ('street', models.CharField(db_column='street', max_length=500)),
                ('number', models.CharField(db_column='number', max_length=500, null=True)),
                ('district', models.CharField(db_column='district', max_length=500)),
                ('city', models.CharField(db_column='city', max_length=500)),
                ('state', models.CharField(db_column='state', max_length=500)),
                ('country', models.CharField(db_column='country', max_length=500)),
            ],
            options={
                'db_table': 'address',
                'managed': True,
                'default_permissions': ('view',),
            },
        ),
    ]
